--Classes
INSERT INTO classe (classe) VALUES ('A');
INSERT INTO classe (classe) VALUES ('B');
INSERT INTO classe (classe) VALUES ('C');
--Roles
INSERT INTO role VALUES
('Responsable achat'),
('Responsable vente'),
('Responsable stock'),
('Employe stock'),
('Responsable SAV'),
('Ressources Humaines'),
('Responsable CRM'),
('Commercant');
--Pays
INSERT INTO pays (nom_pays) VALUES 
('Afghanistan'),
('Afrique du Sud'),
('Albanie'),
('Algérie'),
('Allemagne'),
('Andorre'),
('Angola'),
('Arabie Saoudite'),
('Argentine'),
('Arménie'),
('Australie'),
('Autriche'),
('Azerbaïdjan'),
('Bahamas'),
('Bahreïn'),
('Bangladesh'),
('Belgique'),
('Bénin'),
('Bhoutan'),
('Biélorussie'),
('Birmanie'),
('Bolivie'),
('Bosnie-Herzégovine'),
('Botswana'),
('Brésil'),
('Brunei'),
('Bulgarie'),
('Burkina Faso'),
('Burundi'),
('Cambodge'),
('Cameroun'),
('Canada'),
('Cap-Vert'),
('Chili'),
('Chine'),
('Chypre'),
('Colombie'),
('Comores'),
('Congo (Brazzaville)'),
('Congo (Kinshasa)'),
('Corée du Nord'),
('Corée du Sud'),
('Costa Rica'),
('Côte d’Ivoire'),
('Croatie'),
('Cuba'),
('Danemark'),
('Djibouti'),
('Dominique'),
('Égypte'),
('Émirats arabes unis'),
('Équateur'),
('Érythrée'),
('Espagne'),
('Estonie'),
('Eswatini'),
('États-Unis'),
('Éthiopie'),
('Fidji'),
('Finlande'),
('France'),
('Gabon'),
('Gambie'),
('Géorgie'),
('Ghana'),
('Grèce'),
('Guatemala'),
('Guinée'),
('Guinée équatoriale'),
('Guinée-Bissau'),
('Guyana'),
('Haïti'),
('Honduras'),
('Hongrie'),
('Inde'),
('Indonésie'),
('Irak'),
('Iran'),
('Irlande'),
('Islande'),
('Israël'),
('Italie'),
('Jamaïque'),
('Japon'),
('Jordanie'),
('Kazakhstan'),
('Kenya'),
('Kirghizistan'),
('Kiribati'),
('Koweït'),
('Laos'),
('Lesotho'),
('Lettonie'),
('Liban'),
('Libéria'),
('Libye'),
('Liechtenstein'),
('Lituanie'),
('Luxembourg'),
('Macédoine du Nord'),
('Madagascar'),
('Malaisie'),
('Malawi'),
('Maldives'),
('Mali'),
('Malte'),
('Maroc'),
('Maurice'),
('Mauritanie'),
('Mexique'),
('Micronésie'),
('Moldavie'),
('Monaco'),
('Mongolie'),
('Monténégro'),
('Mozambique'),
('Namibie'),
('Népal'),
('Nicaragua'),
('Niger'),
('Nigéria'),
('Norvège'),
('Nouvelle-Zélande'),
('Oman'),
('Ouganda'),
('Ouzbékistan'),
('Pakistan'),
('Palestine'),
('Panama'),
('Papouasie-Nouvelle-Guinée'),
('Paraguay'),
('Pays-Bas'),
('Pérou'),
('Philippines'),
('Pologne'),
('Portugal'),
('Qatar'),
('République centrafricaine'),
('République tchèque'),
('Roumanie'),
('Royaume-Uni'),
('Russie'),
('Rwanda'),
('Saint-Kitts-et-Nevis'),
('Saint-Marin'),
('Saint-Vincent-et-les-Grenadines'),
('Sainte-Lucie'),
('Salvador'),
('Samoa'),
('Sao Tomé-et-Principe'),
('Sénégal'),
('Serbie'),
('Seychelles'),
('Sierra Leone'),
('Singapour'),
('Slovaquie'),
('Slovénie'),
('Somalie'),
('Soudan'),
('Soudan du Sud'),
('Sri Lanka'),
('Suède'),
('Suisse'),
('Suriname'),
('Syrie'),
('Tadjikistan'),
('Tanzanie'),
('Tchad'),
('Thaïlande'),
('Timor oriental'),
('Togo'),
('Tonga'),
('Trinité-et-Tobago'),
('Tunisie'),
('Turkménistan'),
('Turquie'),
('Tuvalu'),
('Ukraine'),
('Uruguay'),
('Vanuatu'),
('Vatican'),
('Venezuela'),
('Vietnam'),
('Yémen'),
('Zambie'),
('Zimbabwe');